package zserio.extension.diagram.generator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.Set;

import zserio.extension.common.ZserioExtensionException;
import zserio.extension.diagram.DiagramConfig;
import zserio.extension.diagram.model.DiagramModel;
import zserio.extension.diagram.model.EnumItemInfo;
import zserio.extension.diagram.model.FieldInfo;
import zserio.extension.diagram.model.RelationshipInfo;
import zserio.extension.diagram.model.TypeInfo;
import zserio.extension.diagram.model.TypeKind;

/**
 * Generates Mermaid class diagrams from the diagram model.
 */
public class MermaidGenerator implements DiagramGenerator
{
    @Override
    public void setConfig(DiagramConfig config)
    {
        this.config = config;
    }

    @Override
    public String getFileExtension()
    {
        return ".mmd";
    }

    @Override
    public String getFormatName()
    {
        return "Mermaid";
    }

    @Override
    public void generate(DiagramModel model, File outputDir, String baseName) throws ZserioExtensionException
    {
        File outputFile = new File(outputDir, baseName + getFileExtension());
        try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile)))
        {
            generateDiagram(writer, model, model.getAllTypes(), model.getAllRelationships());
            System.out.println("Generated " + getFormatName() + " diagram: " + outputFile.getAbsolutePath());
        }
        catch (IOException e)
        {
            throw new ZserioExtensionException("Failed to write Mermaid file: " + e.getMessage());
        }
    }

    @Override
    public void generatePerPackage(DiagramModel model, File outputDir) throws ZserioExtensionException
    {
        for (String packageName : model.getPackageNames())
        {
            String fileName = packageName.isEmpty() ? "default" : packageName.replace('.', '_');
            File outputFile = new File(outputDir, fileName + getFileExtension());

            List<TypeInfo> packageTypes = model.getTypesInPackage(packageName);
            Set<RelationshipInfo> packageRelationships = model.getRelationshipsInPackage(packageName);

            try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile)))
            {
                generateDiagram(writer, model, packageTypes, packageRelationships);
                System.out.println("Generated " + getFormatName() + " diagram: " + outputFile.getAbsolutePath());
            }
            catch (IOException e)
            {
                throw new ZserioExtensionException("Failed to write Mermaid file: " + e.getMessage());
            }
        }
    }

    private void generateDiagram(PrintWriter writer, DiagramModel model, List<TypeInfo> types,
            Set<RelationshipInfo> relationships)
    {
        writer.println("classDiagram");
        writer.println("    %% Generated by zserio-diagram extension");

        // Direction
        if (config != null && config.getDirection() == DiagramConfig.Direction.LEFT_TO_RIGHT)
        {
            writer.println("    direction LR");
        }

        writer.println();

        // Generate class definitions
        for (TypeInfo type : types)
        {
            generateType(writer, type);
        }

        writer.println();

        // Generate relationships
        for (RelationshipInfo rel : relationships)
        {
            generateRelationship(writer, rel, model);
        }
    }

    private void generateType(PrintWriter writer, TypeInfo type)
    {
        String className = sanitizeName(type.getName());
        String stereotype = type.getKind().getStereotype();

        writer.println("    class " + className + " {");
        writer.println("        <<" + stereotype + ">>");

        switch (type.getKind())
        {
        case ENUM:
        case BITMASK:
            generateEnumOrBitmaskMembers(writer, type);
            break;
        case CONSTANT:
            generateConstantMembers(writer, type);
            break;
        case SUBTYPE:
            generateSubtypeMembers(writer, type);
            break;
        default:
            generateClassMembers(writer, type);
            break;
        }

        writer.println("    }");
        writer.println();
    }

    private void generateClassMembers(PrintWriter writer, TypeInfo type)
    {
        // Note: Parameters are intentionally not output as standalone lines
        // because Mermaid cannot parse "(Type param)" syntax as class members.
        // Instead, we could add them to a note if needed in the future.

        // Fields
        for (FieldInfo field : type.getFields())
        {
            String visibility = field.isOptional() ? "~" : "+";
            String typeName = sanitizeTypeName(field.getDisplayTypeName());
            writer.println("        " + visibility + typeName + " " + field.getName());
        }
    }

    private void generateEnumOrBitmaskMembers(PrintWriter writer, TypeInfo type)
    {
        for (EnumItemInfo item : type.getEnumItems())
        {
            if (item.getValue() != null)
            {
                writer.println("        " + item.getName() + " = " + item.getValue());
            }
            else
            {
                writer.println("        " + item.getName());
            }
        }
    }

    private void generateConstantMembers(PrintWriter writer, TypeInfo type)
    {
        writer.println("        " + type.getUnderlyingType() + " = " + type.getConstantValue() + "$");
    }

    private void generateSubtypeMembers(PrintWriter writer, TypeInfo type)
    {
        writer.println("        alias~" + type.getAliasedTypeName() + "~");
    }

    private void generateRelationship(PrintWriter writer, RelationshipInfo rel, DiagramModel model)
    {
        String sourceType = sanitizeName(getSimpleName(rel.getSourceType()));
        String targetType = sanitizeName(getSimpleName(rel.getTargetType()));

        // Skip relationships to types not in the model (e.g., primitives)
        if (!model.hasType(rel.getTargetType()))
        {
            return;
        }

        String arrow;
        String cardinality = rel.getCardinality();

        switch (rel.getRelationshipType())
        {
        case COMPOSITION:
            arrow = " *-- ";
            break;
        case ASSOCIATION:
            arrow = " --> ";
            break;
        case INHERITANCE:
            arrow = " <|-- ";
            cardinality = "";
            break;
        default:
            arrow = " --> ";
            break;
        }

        StringBuilder line = new StringBuilder();
        line.append("    ");
        line.append(sourceType);

        if (!cardinality.isEmpty())
        {
            line.append(" \"").append(cardinality).append("\"");
        }

        line.append(arrow);
        line.append(targetType);

        if (!rel.getFieldName().isEmpty() && rel.getRelationshipType() != RelationshipInfo.RelationshipType.INHERITANCE)
        {
            line.append(" : ").append(rel.getFieldName());
        }

        writer.println(line);
    }

    private String sanitizeName(String name)
    {
        // Mermaid doesn't like certain characters in names
        // Replace special characters that could break mermaid syntax
        return name.replace("<", "_")
                .replace(">", "_")
                .replace(",", "_")
                .replace(" ", "_")
                .replace("(", "_")
                .replace(")", "_")
                .replace("[", "_")
                .replace("]", "_");
    }

    private String sanitizeTypeName(String typeName)
    {
        // For type names displayed in class members, we need to handle:
        // - Angle brackets from generics/expressions (e.g., bit<N>)
        // - Java object references that might slip through (e.g., @12345)
        // - Other special characters that break Mermaid syntax

        // First, check if this looks like a Java object reference (contains @)
        if (typeName.contains("@"))
        {
            // This is likely an unresolved expression like "zserio.ast.Expression@12345"
            // Extract just the type prefix if possible
            int atIndex = typeName.indexOf("@");
            if (typeName.contains("<") && typeName.indexOf("<") < atIndex)
            {
                // Something like "bit<zserio.ast.Expression@123>"
                String prefix = typeName.substring(0, typeName.indexOf("<"));
                return prefix + "_N";
            }
            return "dynamic";
        }

        // Replace angle brackets with colon notation for cleaner display
        // bit<5> becomes bit:5, bit<numBits> becomes bit:numBits
        String result = typeName.replace("<", ":")
                .replace(">", "");

        return result;
    }

    private String getSimpleName(String fullName)
    {
        int lastDot = fullName.lastIndexOf('.');
        if (lastDot >= 0)
        {
            return fullName.substring(lastDot + 1);
        }
        return fullName;
    }

    private DiagramConfig config;
}
