package zserio.extension.diagram.generator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.Set;

import zserio.extension.common.ZserioExtensionException;
import zserio.extension.diagram.DiagramConfig;
import zserio.extension.diagram.model.DiagramModel;
import zserio.extension.diagram.model.EnumItemInfo;
import zserio.extension.diagram.model.FieldInfo;
import zserio.extension.diagram.model.RelationshipInfo;
import zserio.extension.diagram.model.TypeInfo;
import zserio.extension.diagram.model.TypeKind;

/**
 * Generates PlantUML class diagrams from the diagram model.
 */
public class PlantUmlGenerator implements DiagramGenerator
{
    @Override
    public void setConfig(DiagramConfig config)
    {
        this.config = config;
    }

    @Override
    public String getFileExtension()
    {
        return ".puml";
    }

    @Override
    public String getFormatName()
    {
        return "PlantUML";
    }

    @Override
    public void generate(DiagramModel model, File outputDir, String baseName) throws ZserioExtensionException
    {
        File outputFile = new File(outputDir, baseName + getFileExtension());
        try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile)))
        {
            generateDiagram(writer, model, model.getAllTypes(), model.getAllRelationships(), baseName);
            System.out.println("Generated " + getFormatName() + " diagram: " + outputFile.getAbsolutePath());
        }
        catch (IOException e)
        {
            throw new ZserioExtensionException("Failed to write PlantUML file: " + e.getMessage());
        }
    }

    @Override
    public void generatePerPackage(DiagramModel model, File outputDir) throws ZserioExtensionException
    {
        for (String packageName : model.getPackageNames())
        {
            String fileName = packageName.isEmpty() ? "default" : packageName.replace('.', '_');
            File outputFile = new File(outputDir, fileName + getFileExtension());

            List<TypeInfo> packageTypes = model.getTypesInPackage(packageName);
            Set<RelationshipInfo> packageRelationships = model.getRelationshipsInPackage(packageName);

            try (PrintWriter writer = new PrintWriter(new FileWriter(outputFile)))
            {
                generateDiagram(writer, model, packageTypes, packageRelationships, fileName);
                System.out.println("Generated " + getFormatName() + " diagram: " + outputFile.getAbsolutePath());
            }
            catch (IOException e)
            {
                throw new ZserioExtensionException("Failed to write PlantUML file: " + e.getMessage());
            }
        }
    }

    private void generateDiagram(PrintWriter writer, DiagramModel model, List<TypeInfo> types,
            Set<RelationshipInfo> relationships, String diagramName)
    {
        writer.println("@startuml " + sanitizeName(diagramName));
        writer.println();
        writer.println("' Generated by zserio-diagram extension");

        // Layout engine
        if (config != null)
        {
            switch (config.getLayout())
            {
            case SMETANA:
                writer.println("!pragma layout smetana");
                break;
            case ELK:
                writer.println("!pragma layout elk");
                break;
            default:
                break;
            }

            // Direction
            if (config.getDirection() == DiagramConfig.Direction.LEFT_TO_RIGHT)
            {
                writer.println("left to right direction");
            }

            // Orthogonal lines
            if (config.isOrthoLines())
            {
                writer.println("skinparam linetype ortho");
            }
        }

        writer.println("skinparam classAttributeIconSize 0");
        writer.println("hide empty members");
        writer.println();

        // Group types by package
        String currentPackage = null;
        for (TypeInfo type : types)
        {
            String packageName = type.getPackageName();
            if (packageName == null)
            {
                packageName = "";
            }

            if (!packageName.equals(currentPackage))
            {
                if (currentPackage != null && !currentPackage.isEmpty())
                {
                    writer.println("}");
                    writer.println();
                }
                currentPackage = packageName;
                if (!packageName.isEmpty())
                {
                    writer.println("package \"" + packageName + "\" {");
                }
            }

            generateType(writer, type, !packageName.isEmpty());
        }

        if (currentPackage != null && !currentPackage.isEmpty())
        {
            writer.println("}");
        }

        writer.println();

        // Generate relationships
        for (RelationshipInfo rel : relationships)
        {
            generateRelationship(writer, rel, model);
        }

        writer.println();
        writer.println("@enduml");
    }

    private void generateType(PrintWriter writer, TypeInfo type, boolean indented)
    {
        String indent = indented ? "  " : "";
        String stereotype = type.getKind().getStereotype();

        switch (type.getKind())
        {
        case ENUM:
        case BITMASK:
            generateEnumOrBitmask(writer, type, indent, stereotype);
            break;
        case CONSTANT:
            generateConstant(writer, type, indent);
            break;
        case SUBTYPE:
            generateSubtype(writer, type, indent);
            break;
        default:
            generateClass(writer, type, indent, stereotype);
            break;
        }
        writer.println();
    }

    private void generateClass(PrintWriter writer, TypeInfo type, String indent, String stereotype)
    {
        StringBuilder header = new StringBuilder();
        header.append(indent).append("class ").append(sanitizeName(type.getName()));

        if (!type.getParameters().isEmpty())
        {
            header.append(" <");
            boolean first = true;
            for (String param : type.getParameters())
            {
                if (!first)
                {
                    header.append(", ");
                }
                header.append(param);
                first = false;
            }
            header.append(">");
        }

        header.append(" <<").append(stereotype).append(">> {");
        writer.println(header);

        for (FieldInfo field : type.getFields())
        {
            String visibility = field.isOptional() ? "~" : "+";
            writer.println(indent + "  " + visibility + field.getDisplayTypeName() + " " + field.getName());
        }

        writer.println(indent + "}");
    }

    private void generateEnumOrBitmask(PrintWriter writer, TypeInfo type, String indent, String stereotype)
    {
        writer.println(indent + "enum " + sanitizeName(type.getName()) + " <<" + stereotype + ">> {");

        for (EnumItemInfo item : type.getEnumItems())
        {
            if (item.getValue() != null)
            {
                writer.println(indent + "  " + item.getName() + " = " + item.getValue());
            }
            else
            {
                writer.println(indent + "  " + item.getName());
            }
        }

        writer.println(indent + "}");
    }

    private void generateConstant(PrintWriter writer, TypeInfo type, String indent)
    {
        writer.println(indent + "class " + sanitizeName(type.getName()) + " <<const>> {");
        writer.println(indent + "  {static} " + type.getUnderlyingType() + " = " + type.getConstantValue());
        writer.println(indent + "}");
    }

    private void generateSubtype(PrintWriter writer, TypeInfo type, String indent)
    {
        writer.println(indent + "class " + sanitizeName(type.getName()) + " <<subtype>> {");
        writer.println(indent + "  alias of " + type.getAliasedTypeName());
        writer.println(indent + "}");
    }

    private void generateRelationship(PrintWriter writer, RelationshipInfo rel, DiagramModel model)
    {
        String sourceType = getSimpleName(rel.getSourceType());
        String targetType = getSimpleName(rel.getTargetType());

        // Skip relationships to types not in the model (e.g., primitives)
        if (!model.hasType(rel.getTargetType()))
        {
            return;
        }

        String arrow;
        String cardinality = rel.getCardinality();

        switch (rel.getRelationshipType())
        {
        case COMPOSITION:
            arrow = " *-- ";
            break;
        case ASSOCIATION:
            arrow = " --> ";
            break;
        case INHERITANCE:
            arrow = " <|-- ";
            cardinality = "";
            break;
        default:
            arrow = " --> ";
            break;
        }

        StringBuilder line = new StringBuilder();
        line.append(sanitizeName(sourceType));
        line.append(arrow);

        if (!cardinality.isEmpty())
        {
            line.append("\"").append(cardinality).append("\" ");
        }

        line.append(sanitizeName(targetType));

        if (!rel.getFieldName().isEmpty() && rel.getRelationshipType() != RelationshipInfo.RelationshipType.INHERITANCE)
        {
            line.append(" : ").append(rel.getFieldName());
        }

        writer.println(line);
    }

    private String sanitizeName(String name)
    {
        // PlantUML doesn't like certain characters in names
        return name.replace("<", "_").replace(">", "_").replace(",", "_").replace(" ", "_");
    }

    private String getSimpleName(String fullName)
    {
        int lastDot = fullName.lastIndexOf('.');
        if (lastDot >= 0)
        {
            return fullName.substring(lastDot + 1);
        }
        return fullName;
    }

    private DiagramConfig config;
}
